name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  banner: ^0.1.3
  dio: ^2.1.13
  flutter_webview_plugin: ^0.3.5
  flutter_easyrefresh: ^1.2.7
  flutter_staggered_grid_view: "^0.2.7"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/me_icon_shouye.png
    - images/me_icon_faxian.png
    - images/me_icon_wo.png
    - images/huime_icon_shouye.png
    - images/huime_icon_wo.png
    - images/huime_icon_faxian.png
    - images/icon_like.png
    - images/ani_1.png
    - images/ani_2.png
    - images/ani_3.png
    - images/ani_4.png
    - images/ani_5.png
    - images/ani_6.png
    - images/ani_7.png
    - images/ani_8.png
    - images/ani_9.png
    - images/ani_10.png
    - images/ani_11.png
    - images/ani_12.png
    - images/ani_13.png
    - images/ani_14.png
    - images/ani_15.png
    - images/ani_16.png
    - images/ani_17.png
    - images/ani_18.png
    - images/ani_19.png
    - images/ani_20.png
    - images/ani_21.png
    - images/ani_22.png
    - images/ani_23.png
    - images/ani_24.png
    - images/ani_25.png
    - images/ani_26.png
    - images/ani_27.png
    - images/ani_28.png
    - images/ani_29.png
    - images/ani_30.png
    - images/ani_31.png
    - images/ani_32.png
    - images/icon_author.png
    - images/right_arrow.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
